language: objective-c
before_install:
    - cd Example
    - brew update
    - brew uninstall xctool
    - brew install xctool
    - pod install
script:
    - xctool -workspace PreferredBrowserExample.xcworkspace -scheme PreferredBrowserExample -sdk iphonesimulator build ONLY_ACTIVE_ARCH=NO
